export const SCREEN_MAX_VISIBLE_TILE_X = 64;
export const SCREEN_MAX_VISIBLE_TILE_Y = 48;

export const SPRITES_TEXTURE_SIZE = 1024;
export const SPRITE_SIZE = 32;
export const SPRITES_PER_TEXTURE_AXIS = Math.floor(SPRITES_TEXTURE_SIZE / SPRITE_SIZE);
export const SPRITES_PER_TEXTURE = SPRITES_PER_TEXTURE_AXIS ** 2;
export const SPRITE_STRIDE_NORMALIZED = SPRITE_SIZE / SPRITES_TEXTURE_SIZE;

export const MAX_CHUNKS_PER_SPACE_AXIS = 65536;
export const MAX_SPACE_DEPTH = 65536;

export const TILE_SIZE = 32;
export const TILES_PER_CHUNK_GRID_AXIS = 32;
export const TILES_PER_CHUNK_GRID = TILES_PER_CHUNK_GRID_AXIS ** 2;

export const PIXELS_PER_CHUNK_GRID_AXIS = TILES_PER_CHUNK_GRID_AXIS * SPRITE_SIZE;
export const PIXELS_PER_CHUNK_GRID = PIXELS_PER_CHUNK_GRID_AXIS ** 2;
export const LAYERS_PER_CHUNK = 16;

export const POSITIONS_SAMPLING_PER_CHUNK_AXIS = 0x4000;
export const POSITIONS_SAMPLING_PER_PIXEL = Math.floor(POSITIONS_SAMPLING_PER_CHUNK_AXIS / TILES_PER_CHUNK_GRID_AXIS / SPRITE_SIZE);

export const ERROR_GAME_OBJECT_SPRITE_INDEX = 0;
export const UNDEFINED_GAME_OBJECT_SPRITE_INDEX = 1;
export const DEFAULT_GAME_OBJECT_SPRITE_INDEX = 2;
